#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: tkg-clusterclass-infra-values
  namespace: tkg-system
type: Opaque
stringData:
  values.yaml: #@ yaml.encode(data.values.configvalues)
