#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Secret
metadata:
  name: tkg-clusterclass-infra-values
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting v1/serviceaccount"
    kapp.k14s.io/change-rule.1: "delete before deleting v1/serviceaccount"
type: Opaque
stringData:
  values.yaml: #@ yaml.encode(data.values.configvalues)
