---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-aws-clusterclass-package-sa
  namespace: tkg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-aws-clusterclass-package-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusterclasses
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - packaging.carvel.dev
    resources:
      - packageinstalls
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - update
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-aws-clusterclass-package-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-aws-clusterclass-package-cluster-role
subjects:
  - kind: ServiceAccount
    name: tanzu-aws-clusterclass-package-sa
    namespace: tkg-system