---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-infra-clusterclass-package-sa
  namespace: tkg-system
  annotations:
    kapp.k14s.io/change-group: "v1/sa-tkg-clusterclass-pkg"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-infra-clusterclass-package-cluster-role
  annotations:
    kapp.k14s.io/change-group: "v1/sa-tkg-clusterclass-pkg"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - serviceaccounts
      - services
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusterclasses
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - bootstrap.cluster.x-k8s.io
    resources:
      - kubeadmconfigtemplates
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - awsmachinetemplates
      - awsclustertemplates
      - vspheremachinetemplates
      - vsphereclustertemplates
      - azuremachinetemplates
      - azureclustertemplates
      - dockermachinetemplates
      - dockerclustertemplates
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - controlplane.cluster.x-k8s.io
    resources:
      - kubeadmcontrolplanetemplates
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - packaging.carvel.dev
    resources:
      - packageinstalls
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - update
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-infra-clusterclass-package-cluster-rolebinding
  annotations:
    kapp.k14s.io/change-group: "v1/sa-tkg-clusterclass-pkg"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-infra-clusterclass-package-cluster-role
subjects:
  - kind: ServiceAccount
    name: tanzu-infra-clusterclass-package-sa
    namespace: tkg-system
