apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: context-aware-cliplugins.tanzu.vmware.com
  namespace: context-aware-cliplugins
spec:
  refName: context-aware-cliplugins.tanzu.vmware.com
  version: VERSION
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: # Get this value by pushing to your OCI Registry
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
