#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: tkg-azure-clusterclass
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: tkg-kcp
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureMachineTemplate
        name: tkg-controlplane-azure-template
  workers:
    machineDeployments:
    - class: tkg-worker
      template:
         bootstrap:
           ref:
             apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
             kind: KubeadmConfigTemplate
             name: tkg-bootstrap-template
         infrastructure:
           ref:
             apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
             kind: AzureMachineTemplate
             name: tkg-azure-template
  infrastructure:
     ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterTemplate
        name: azure-cluster-template
  variables:
  - name: AZURE_LOCATION
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_LOCATION:
        default: #@ data.values.configvalues.AZURE_LOCATION
        #@ end
  - name: AZURE_VNET_NAME
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_VNET_NAME:
        default: #@ data.values.configvalues.AZURE_VNET_NAME
        #@ end
  - name: AZURE_VNET_CIDR
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_VNET_CIDR:
        default: #@ data.values.configvalues.AZURE_VNET_CIDR
        #@ end
  - name: AZURE_CONTROL_PLANE_SUBNET_NAME
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_CONTROL_PLANE_SUBNET_NAME:
        default: #@ data.values.configvalues.AZURE_CONTROL_PLANE_SUBNET_NAME
        #@ end
  - name: AZURE_CONTROL_PLANE_SUBNET_CIDR
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_CONTROL_PLANE_SUBNET_CIDR:
        default: #@ data.values.configvalues.AZURE_CONTROL_PLANE_SUBNET_CIDR
        #@ end
  - name: AZURE_NODE_SUBNET_NAME
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_NODE_SUBNET_NAME:
        default: #@ data.values.configvalues.AZURE_NODE_SUBNET_NAME
        #@ end
  - name: AZURE_NODE_SUBNET_CIDR
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_NODE_SUBNET_CIDR:
        default: #@ data.values.configvalues.AZURE_NODE_SUBNET_CIDR
        #@ end
  - name: AZURE_RESOURCE_GROUP
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_RESOURCE_GROUP:
        default: #@ data.values.configvalues.AZURE_RESOURCE_GROUP
        #@ end
  - name: AZURE_SUBSCRIPTION_ID
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.AZURE_SUBSCRIPTION_ID:
        default: #@ data.values.configvalues.AZURE_SUBSCRIPTION_ID
        #@ end
  - name: CLUSTER_NAME
    required: true
    schema:
      openAPIV3Schema:
        type: string
        #@ if data.values.configvalues.CLUSTER_NAME:
        default: #@ data.values.configvalues.CLUSTER_NAME
        #@ end

  patches:
  - name: ACT_main
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: replace
        path: "/spec/template/spec/identityRef/name"
        valueFrom:
          template: '{{.CLUSTER_NAME}}-identity'
      - op: replace
        path: "/spec/template/spec/location"
        valueFrom:
          template: '{{.AZURE_LOCATION}}'
      - op: replace
        path: "/spec/template/spec/networkSpec/vnet"
        valueFrom:
          template: |
            name: {{.CLUSTER_NAME}}-vnet
            # TODO (AZURE_VNET_RESOURCE_GROUP optionally)
            resourceGroup: {{.CLUSTER_NAME}}
            cidrBlocks: [{{.AZURE_VNET_CIDR}}]
      - op: replace
        path: "/spec/template/spec/resourceGroup"
        valueFrom:
          variable: CLUSTER_NAME
      - op: replace
        path: "/spec/template/spec/subscriptionID"
        valueFrom:
          variable: AZURE_SUBSCRIPTION_ID
      - op: replace
        path: "/spec/template/spec/networkSpec/subnets"
        valueFrom:
          template: |
            - name: {{ .AZURE_CONTROL_PLANE_SUBNET_NAME }}
              role: control-plane
              cidrBlocks: [{{ .AZURE_CONTROL_PLANE_SUBNET_CIDR }}]
            - name: {{ .AZURE_NODE_SUBNET_NAME }}
              role: node
              cidrBlocks: [{{ .AZURE_NODE_SUBNET_CIDR }}]
  - name: ACT_optional
    enabledIf: '{{if .AZURE_RESOURCE_GROUP}}true{{end}}'
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: replace
        path: "/spec/template/spec/resourceGroup"
        valueFrom:
          variable: AZURE_RESOURCE_GROUP

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterTemplate
metadata:
  name: azure-cluster-template
  namespace: default
spec:
  template:
    spec:
      identityRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterIdentity
        name: xxcnamexx-identity
        namespace: tkg-system
      location: ${AZURE_LOCATION}
      networkSpec:
        vnet:
          name: "${AZURE_VNET_NAME:=${CLUSTER_NAME}-vnet}"
          resourceGroup: ${AZURE_VNET_RESOURCE_GROUP:=${CLUSTER_NAME}}
          cidrBlock: ${AZURE_VNET_CIDR}
        subnets:
          - name: ${AZURE_CONTROL_PLANE_SUBNET_NAME}
            role: control-plane
            cidrBlock: ${AZURE_CONTROL_PLANE_SUBNET_CIDR}
          - name: ${AZURE_NODE_SUBNET_NAME}
            role: node
            cidrBlock: ${AZURE_NODE_SUBNET_CIDR}
      resourceGroup: ${AZURE_RESOURCE_GROUP:=${CLUSTER_NAME}}
      subscriptionID: ${AZURE_SUBSCRIPTION_ID}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: tkg-kcp
  namespace: default
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-config: /etc/kubernetes/azure.json
              cloud-provider: azure
            extraVolumes:
              - hostPath: /etc/kubernetes/azure.json
                mountPath: /etc/kubernetes/azure.json
                name: cloud-config
                readOnly: true
            timeoutForControlPlane: 20m
          controllerManager:
            extraArgs:
              allocate-node-cidrs: "true"
              cloud-config: /etc/kubernetes/azure.json
              cloud-provider: azure
              cluster-name: ${CLUSTER_NAME}
            extraVolumes:
              - hostPath: /etc/kubernetes/azure.json
                mountPath: /etc/kubernetes/azure.json
                name: cloud-config
                readOnly: true
          dns:
            imageRepository: projects-stg.registry.vmware.com/tkg #! TODO '${_TKG_COREDNS_IMAGE_REPOSITORY}' May be a variable for package level 
            imageTag: v1.8.4_vmware.5 #! TODO '${_TKG_COREDNS_IMAGE_TAG}' May be a variable for package level 
          etcd:
            local:
              dataDir: /var/lib/etcddisk/etcd
              imageRepository: projects-stg.registry.vmware.com/tkg #! TODO '${_TKG_ETCD_IMAGE_REPOSITORY}' May be a variable for package level 
              imageTag: v3.5.0_vmware.5 #! TODO '${_TKG_ETCD_IMAGE_TAG}' May be a variable for package level 
              extraArgs:
                cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          imageRepository: projects-stg.registry.vmware.com/tkg #! TODO '${_TKG_COREDNS_IMAGE_REPOSITORY}' May be a variable for package level
        diskSetup:
          filesystems:
          - device: /dev/disk/azure/scsi1/lun0
            extraOpts:
            - -E
            - lazy_itable_init=1,lazy_journal_init=1
            filesystem: ext4
            label: etcd_disk
          - device: ephemeral0.1
            filesystem: ext4
            label: ephemeral0
            replaceFS: ntfs
          partitions:
          - device: /dev/disk/azure/scsi1/lun0
            layout: true
            overwrite: false
            tableType: gpt
        files:
        - contentFrom:
            secret:
              key: control-plane-azure.json
              name: ${CLUSTER_NAME}-control-plane-azure-json
          owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              azure-container-registry-config: /etc/kubernetes/azure.json
              cloud-config: /etc/kubernetes/azure.json
              cloud-provider: azure
            name: '{{ ds.meta_data["local_hostname"] }}'
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              azure-container-registry-config: /etc/kubernetes/azure.json
              cloud-config: /etc/kubernetes/azure.json
              cloud-provider: azure
            name: '{{ ds.meta_data["local_hostname"] }}'
        mounts:
          - - LABEL=etcd_disk
            - /var/lib/etcddisk
        useExperimentalRetryJoin: true
        postKubeadmCommands: []
        preKubeadmCommands: []
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: tkg-controlplane-azure-template
  namespace: default
spec:
  template:
    spec:
      dataDisks:
        - diskSizeGB: 256
          lun: 0
          nameSuffix: etcddisk
      image:
         id: image_id
      osDisk:
        diskSizeGB: 128
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
      vmSize: ${AZURE_CONTROL_PLANE_MACHINE_TYPE}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: tkg-azure-template
  namespace: default
spec:
  template:
    spec:
      osDisk:
        diskSizeGB: 128
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      image:
         id: image_id
      sshPublicKey: ${AZURE_SSH_PUBLIC_KEY_B64:=""}
      vmSize: ${AZURE_NODE_MACHINE_TYPE}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: tkg-bootstrap-template
  namespace: default
spec:
  template:
    spec:
      files:
        - contentFrom:
            secret:
              key: worker-node-azure.json
              #! VVVV TODO(vui)
              name: tkg-md-0-azure-json
          owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            azure-container-registry-config: /etc/kubernetes/azure.json
            cloud-config: /etc/kubernetes/azure.json
            cloud-provider: azure
          name: '{{ ds.meta_data["local_hostname"] }}'
      useExperimentalRetryJoin: true
      preKubeadmCommands: []
