#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tkg-clusterclass
  namespace: tkg-system
spec:
  serviceAccountName: tanzu-tkg-package-sa
  packageRef:
    refName: tkg-clusterclass.tanzu.vmware.com
    versionSelection:
      prereleases: {}
  values:
  - secretRef:
      name: tkg-clusterclass-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tkg-clusterclass-values
  namespace: tkg-system
type: Opaque
stringData:
  values.yaml: #@ yaml.encode(data.values.configvalues)