apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: clusterclass-aws.tanzu.vmware.com
  namespace: clusterclass-aws
spec:
  refName: clusterclass-aws.tanzu.vmware.com
  version: latest
  releaseNotes: "relevant release notes..."
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: # Get this value by pushing to your OCI Registry
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
