#@data/values
---

#! User configurable values for tkg.

metadata:
  infraProvider: ""

configvalues:

tkrPackageRepository:
  imageRepository: ""
  imagePath: ""
  versionConstraints: ">1.22.0"

frameworkPackage:
  namespaceForPackageInstallation: tkg-system
  versionConstraints:
  featureGatesPackageValues:
    namespace: tkg-system
    createNamespace: false
    versionConstraints:
    deployment:
      hostNetwork: true
      nodeSelector: null
      tolerations: []
  tkrServicePackageValues:
    namespace: tkg-system
    createNamespace: false
    versionConstraints:
  addonsManagerPackageValues:
    versionConstraints:
    tanzuAddonsManager:
      namespace: tkg-system
      createNamespace: false
      deployment:
        hostNetwork: true
        priorityClassName: system-cluster-critical
        nodeSelector: null
        tolerations: []
        healthzPort: 18316
      featureGates:
        clusterBootstrapController: false
  clipluginsPackageValues:
    namespace: tkg-system
    versionConstraints:

clusterclassPackage:
  namespaceForPackageInstallation: tkg-system
  versionConstraints:
  clusterclassInfraPackageValues:
    namespace: tkg-system
    createNamespace: false
    versionConstraints:
