---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/login-darwin-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/login-darwin-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/login-darwin-amd64@sha256:443df31fec8f78b55ea25ac1ba55907567fbdf05301a752e9f6adefe3c37e11d
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/login-linux-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/login-linux-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/login-linux-amd64@sha256:53fb40d45e6a1267713cfdd6b561a65457cd5a575c6813fbdae06380b48e5e1f
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/login-windows-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/login-windows-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/login-windows-amd64@sha256:d038e5ac41f88c6bc52671da15d31eb3d25954dc29ed604b552294005c8c8101
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/management-cluster-darwin-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/management-cluster-darwin-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/management-cluster-darwin-amd64@sha256:46f405f246b22d6167e7c4dd38e05852c28ce47a785fed197939d6de5a8a25b7
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/management-cluster-linux-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/management-cluster-linux-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/management-cluster-linux-amd64@sha256:f8d016b11a7e31763ca3a0fce943a2fc4e1fc5315a9e06f9ddc2f1e644b17138
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/management-cluster-windows-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/management-cluster-windows-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/management-cluster-windows-amd64@sha256:c53fc605d241944189813aaf460de8ed8b4de93609e07437191d72dc71e201d6
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/package-darwin-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/package-darwin-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/package-darwin-amd64@sha256:67345a5957a6a387cbe8b0f23134873cdf437e4a2120eeda472d2a21f9ff24e9
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/package-linux-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/package-linux-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/package-linux-amd64@sha256:d8dc1f771a1f16bfa7133d61d58971727edbfade2743a52413728169fbf8ee24
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/package-windows-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/package-windows-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/package-windows-amd64@sha256:c47fa1f7bf59cc87e9d3d654b6b5b9e63ba203a735caa5c7416f33db3acd24bb
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/pinniped-auth-darwin-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/pinniped-auth-darwin-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/pinniped-auth-darwin-amd64@sha256:ed51ae1a46a7b428fe752dd500c3edc5d376df2f6d182aa519f4d4728b04ec92
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/pinniped-auth-linux-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/pinniped-auth-linux-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/pinniped-auth-linux-amd64@sha256:21ddf6caa22c8834d8f32d2654f6c9e219166b91ade508b0dd939d3693eea8d4
- annotations:
    kbld.carvel.dev/id: tanzu-cli-plugins/pinniped-auth-windows-amd64:latest
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.9.0-dev
          url: localhost:5000/tanzu-cli-plugins/pinniped-auth-windows-amd64:v0.9.0-dev
  image: localhost:5000/tanzu-cli-plugins/pinniped-auth-windows-amd64@sha256:abee9304e6422230922fa82058d7922eaca834f787c7d33d1f6974e7fbebc9ac
kind: ImagesLock
